Cmake Placement
NovaMods/nova-renderer pull request #108
Opened 2018-01-31 15:29 UTC by coler706

2018-01-31 16:00 UTC, DethRaid requested changes

2018-01-31 16:00 UTC, DethRaid commented on build.gradle
> +task buildDll(type: Exec){//, dependsOn: invokeCMake) {
Just remove the code

2018-01-31 16:00 UTC, DethRaid commented on src/main/cpp/render/nova_renderer.cpp
> +                                                                               UINT32_MAX,
Would rather undef max in this file

2018-02-01 12:23 UTC, skmedix requested changes

2018-02-01 12:23 UTC, skmedix commented on src/main/cpp/CMakeSettings.json
> +  // See https://go.microsoft.com//fwlink//?linkid=834763 for more information about this file.
`"_comment": "See https://go.microsoft.com//fwlink//?linkid=834763 for more information about this file.",`

2018-02-01 12:23 UTC, skmedix commented on setup.gradle
> +
A new line is not necessary here

2018-02-02 05:33 UTC, DethRaid requested changes

2018-02-02 05:33 UTC, DethRaid commented on src/main/cpp/CMakeSettings.json
> +}
Wait why did you commit this file

Don't commit this file

2018-02-07 01:18 UTC, closed without merging