Clang Tidy and Clang Format
NovaMods/nova-renderer pull request #186
Opened 2019-02-12 00:13 UTC by cwfitzgerald

This is a monster PR. 75 commits. In an effort to make this readable, I have split this into commits by change type. A brief guide for reviewing this:

- Commits starting with `clang-tidy:` are a direct result of the named clang-tidy check. There is no more than one of these checks per commit.
- The commits names `THICC: Apply automatic clang-tidy-fixes` and `reformat` are very large, programmatic changes. These should most likely be skimmed, but reading the entire thing will bore you to death. If there is a problem with formatting, that is outside of the scope of this PR.
- Windows is broken. It will be fixed shortly. Windows headers are extremely include order sensitive.

Major Changes:
- Added `format` `reformat`, `lint`, `lint-by-file`, `lint-by-diagnostic`, and `lint-fix` targets.
- Boosted warnings up to `-Wall -Wextra -Wpedantic -Wconversion -Werror`
- Moved gtest into 3rd party folder to prevent warning fall through.
- Automatic build failure on lack of formatting or warnings from any compiler.

2019-02-12 17:02 UTC, DethRaid requested changes
Looks like the clang-format file still needs a little tweaking

2019-02-12 17:02 UTC, DethRaid commented on .clang-tidy
> +User:            connor
Shouldn't the user still be Nova? Alternately, what's the meaning of the User variable?

2019-02-12 17:02 UTC, DethRaid commented on .gitmodules
> +	path = 3rdparty/googletest
We had put googletest under the tests directory because only the tests depend on it

2019-02-12 17:02 UTC, DethRaid commented on src/debugging/renderdoc.cpp
>  #ifdef ERROR
Why didn't you change this one to `if defined()`?

2019-02-12 17:02 UTC, DethRaid commented on src/debugging/renderdoc.cpp
> +#include <dlfcn.h>
I thought system headers usually went first

2019-02-12 17:02 UTC, DethRaid commented on src/debugging/renderdoc.cpp
> +    RENDERDOC_API_1_3_0 *load_renderdoc(const std::string &renderdoc_dll_path) {
Actually the * and & should be on the left, next to the type, following with the C++ core guidelines

2019-02-12 17:02 UTC, DethRaid commented on src/loading/folder_accessor.cpp
> +    }
Shouldn't put the closing curly brace on a new line if the body is empty

2019-02-12 17:02 UTC, DethRaid commented on src/loading/folder_accessor.hpp
> +        [[nodiscard]] const char *what() const noexcept override {
What does nodiscard mean and why do we need it?

2019-02-12 17:02 UTC, DethRaid commented on src/loading/json_utils.hpp
> +    std::optional<ValType> get_json_value(const nlohmann::json &json_obj,
I feel like this line has an absurd amount of trailing whitespace but I can't tell from a GitHub diff on mobile

2019-02-12 17:02 UTC, DethRaid commented on src/loading/shaderpack/json_interop.hpp
> +    void from_json(const nlohmann::json &j, material_data &mat);
Good catch!

2019-02-12 17:46 UTC, cwfitzgerald commented on .clang-tidy
> +User:            connor
Yes, fixed in later commit.

It's used for one check that forces you to add your name to todos:

```
// TODO(connor): Blah
```

But that's off, so doesn't matter.

2019-02-12 17:47 UTC, cwfitzgerald commented on .gitmodules
> +	path = 3rdparty/googletest
I know, but for a slew of reasons, 3rd party deps really need to be self contained within /3rdparty. That being said, I can turn off the googletest import if you aren't building tests.

2019-02-12 17:48 UTC, cwfitzgerald commented on src/debugging/renderdoc.cpp
>  #ifdef ERROR
Fixed later.

2019-02-12 17:50 UTC, cwfitzgerald commented on src/debugging/renderdoc.cpp
> +#include <dlfcn.h>
That's the way clang-format/tidy like them. There's no real solid argument one way or the other as you shouldn't need any system headers for your own headers. Shouldn't:tm:.

2019-02-12 17:51 UTC, cwfitzgerald commented on src/debugging/renderdoc.cpp
> +    RENDERDOC_API_1_3_0 *load_renderdoc(const std::string &renderdoc_dll_path) {
Fixed.

2019-02-12 17:51 UTC, cwfitzgerald commented on src/loading/folder_accessor.cpp
> +    }
Fixed.

2019-02-12 17:52 UTC, cwfitzgerald commented on src/loading/folder_accessor.hpp
> +        [[nodiscard]] const char *what() const noexcept override {
`nodiscard` warns if you ignore the return value. Void cast counts as a use, so if you really want to override it on a case by case basis you can, but it's a good default to have.

2019-02-12 17:53 UTC, cwfitzgerald commented on src/loading/json_utils.hpp
> +    std::optional<ValType> get_json_value(const nlohmann::json &json_obj,
Doesn't

2019-02-12 17:53 UTC, DethRaid commented on .gitmodules
> +	path = 3rdparty/googletest
Turning it off if you're not building tests would be wonderful

2019-02-12 17:54 UTC, DethRaid commented on src/debugging/renderdoc.cpp
> +#include <dlfcn.h>
And there's no setting? Ugh

2019-02-12 17:56 UTC, DethRaid commented on src/loading/json_utils.hpp
> +    std::optional<ValType> get_json_value(const nlohmann::json &json_obj,
Probably just the mobile website being weird

2019-02-12 18:02 UTC, cwfitzgerald commented on src/debugging/renderdoc.cpp
> +#include <dlfcn.h>
Wait, no it's fully customizable, you set regexes for an include and give it a category number, things go in category number, then alpha within category.

2019-02-12 18:20 UTC, cwfitzgerald commented on src/loading/folder_accessor.cpp
> +    }
Your choice seems to be that it considers that function as non empty, so you either get all one-line-able functions on one line, or you get stuff like this here and there.

2019-02-15 20:32 UTC, DethRaid requested changes

2019-02-15 20:32 UTC, DethRaid commented on src/debugging/renderdoc.cpp
> +#    include "../util/windows.hpp"
I don't know how I missed this the first time I reviewed but can we not separate the # and the token? Like, I have never done this in my code and I don't know why clang-format thought it was okay

2019-02-20 04:23 UTC, DethRaid approved these changes

2019-02-20 04:39 UTC, merged