Use vcpkg for dependencies
NovaMods/nova-renderer pull request #188
Opened 2019-03-07 06:41 UTC by DethRaid

2019-03-07 07:33 UTC, cwfitzgerald requested changes
Almost done, I think we just need to unfuck appveyor and jenkins once the final PR to vcpkg gets cleared

2019-03-07 07:33 UTC, cwfitzgerald commented on CMakeLists.txt
>                       ${Vulkan_LIBRARIES})
Doesn't need to be here if Vulkan::Vulkan is there.

2019-03-07 07:33 UTC, cwfitzgerald commented on readme.md
> +Generate your compiler's build files from the CMake project. We recommend creating your build files in a `build` directory in the root of your local Nova Renderer repository. Be sure to pass CMake th
This could use some examples of how to do that.

2019-03-07 07:33 UTC, cwfitzgerald commented on setup-linux.sh
> +vcpkg install miniz:x64-linux fmt:x64-linux glm:x64-linux glslang:x64-linux gtest:x64-linux nlohmann-json:x64-linux spirv-cross:x64-linux spirv-tools:x64-linux vulkan-memory-allocator:x64-linux vulka
End of line

2019-03-07 07:33 UTC, cwfitzgerald commented on setup-windows.ps1
> +vcpkg install miniz:x64-windows fmt:x64-windows glm:x64-windows glslang:x64-windows gtest:x64-windows nlohmann-json:x64-windows spirv-cross:x64-windows spirv-tools:x64-windows vulkan-memory-allocator
End of line

2019-03-07 21:30 UTC, cwfitzgerald submitted a review, later dismissed

2019-03-14 02:32 UTC, DethRaid commented
CI can't build this PR until https://github.com/Microsoft/vcpkg/pull/5577 is merged

2019-03-15 22:57 UTC, DethRaid commented
test this please

2019-03-16 01:25 UTC, DethRaid commented
test this please

2019-03-16 04:43 UTC, cwfitzgerald commented
Merging blocked until https://github.com/Microsoft/vcpkg/pull/5699 merged.

2019-03-19 02:27 UTC, cwfitzgerald approved these changes

2019-03-19 02:28 UTC, merged