Quick fixes
NovaMods/nova-renderer pull request #189
Opened 2019-03-16 23:19 UTC by Janrupf

some really small fixes for issues discovered while working on the java wrapper

2019-03-17 05:26 UTC, DethRaid requested changes

2019-03-17 05:26 UTC, DethRaid commented on src/render_engine/vulkan/vulkan_render_engine_init.cpp
> +    vulkan_render_engine::vulkan_render_engine(const nova_settings& n_settings, nova::ttl::task_scheduler* task_scheduler)
Don't need to change the name. The compiler is able to disambiguate `settings` from `this->settings` in the constructor's initializer list

2019-03-17 05:26 UTC, DethRaid commented
Is this expected to fail CI?

2019-03-17 05:27 UTC, cwfitzgerald commented
Yes. CI assumes vcpkg branch or a child thereof.

2019-03-18 14:19 UTC, DethRaid approved these changes

2019-03-18 17:19 UTC, cwfitzgerald commented
Overrriding tests due to broken tests, merging.

2019-03-18 17:20 UTC, merged