Feature/windows clang
NovaMods/nova-renderer pull request #265
Opened 2020-04-18 19:03 UTC by Janrupf

This makes the windows CI build use clang cl. Currently it doesn't build because of some compilation error, but it now uses clang-cl and Ninja on windows.

2020-04-18 19:57 UTC, DethRaid approved these changes
LGTM

2020-04-18 20:01 UTC, cwfitzgerald requested changes

2020-04-18 20:01 UTC, cwfitzgerald commented on .github/workflows/ci.yml
> +          ls
Left in a `ls`

2020-04-18 20:07 UTC, DethRaid commented
Also really need to add `-Wno-documentation` to the build args

2021-01-07 23:34 UTC, DethRaid commented
nah

2021-01-07 23:34 UTC, closed without merging